# Generated by Django 4.0.1 on 2022-01-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_answer_id_alter_examname_id_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examname',
            name='created',
        ),
        migrations.RemoveField(
            model_name='examname',
            name='updated',
        ),
    ]
