# Generated by Django 4.0.1 on 2022-01-20 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_examname_created_remove_examname_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='examname',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examname',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
