# Generated by Django 4.0.1 on 2022-01-21 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_answer_correct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Answer', 'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='examname',
            options={'verbose_name': 'Exam Name', 'verbose_name_plural': "Exam's Name"},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='text',
            new_name='options',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='Question',
        ),
    ]
