# Generated by Django 4.0.1 on 2022-01-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_answer_options_alter_examname_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Question',
            new_name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='sn',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
